syntax = "proto3";

package chat.v1;

import "google/protobuf/timestamp.proto";

// message InboxRequests {
//   oneof content {
//     SendMessageRequest send_message_request = 1;
//   }
// }

// message InboxResponses {
//   oneof content {
//     SendMessageResponse send_message_response = 1;
//     InboxErrorType error = 2;
//   }
// }

// enum InboxErrorType {
//   ROOM_ERROR_TYPE_UNSPECIFIED = 0;
//   ROOM_ERROR_TYPE_AUTH = 1;
//   ROOM_ERROR_TYPE_NOROOM = 2;
// }

message Chat{
  int64 chat_room_id = 1;
  string chat_type = 2;
  int64 other_person_id = 3;
  string other_person_name = 4;
  google.protobuf.Timestamp updated_at = 5;
}

// message SendMessageRequest {
//   string content = 1;
//   int64 chat_id = 2;
// }
// message SendMessageResponse {
//   Message message = 1;
// }

message Message {
  int64 id = 1;
  int64 chat_id = 2;
  string content = 3;
  int64 sender_person_id = 4;
  google.protobuf.Timestamp sent_at = 5;
  google.protobuf.Timestamp edited_at = 6;
  google.protobuf.Timestamp deleted_at = 7;
}


// GetAllChats        → inbox
// GetMessages        → thread (cursor/limit)
// SendMessage        → send + return created message
// MarkRead           → optional but nice early (you have SetLastReadId SQL)
service ChatService {
  rpc GetAllChats(GetAllChatsRequest) returns (GetAllChatsResponse) {}
  rpc GetMessages(GetMessagesRequest) returns (GetMessagesResponse) {}
  rpc SendMessage(SendMessageRequest) returns (SendMessageResponse) {}
}

message GetAllChatsRequest {
}

message GetAllChatsResponse {
  repeated Chat chats = 1;
}

message GetMessagesRequest {
  int64 chat_id = 1;
  google.protobuf.Timestamp last_message_timestamp = 2;
}

message GetMessagesResponse {
  repeated Message messages = 1;
}

message SendMessageRequest {
  int64 chat_id = 1;
  string content = 2;
}

message SendMessageResponse {
  Message message = 1;
}