// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: room_games.sql

package database

import (
	"context"
)

const createRoomGame = `-- name: CreateRoomGame :one
INSERT INTO room_games (room_id,game_type) VALUES ($1,$2) RETURNING id, room_id, game_type, started_at, ended_at, status
`

type CreateRoomGameParams struct {
	RoomID   int
	GameType string
}

func (q *Queries) CreateRoomGame(ctx context.Context, arg CreateRoomGameParams) (RoomGame, error) {
	row := q.db.QueryRow(ctx, createRoomGame, arg.RoomID, arg.GameType)
	var i RoomGame
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.GameType,
		&i.StartedAt,
		&i.EndedAt,
		&i.Status,
	)
	return i, err
}
