syntax = "proto3";

package friends.v1;

import "account/v1/account.proto";


service FriendsService {
  rpc SearchForUsername(SearchForUsernameRequest) returns (SearchForUsernameResponse) {};
  rpc GetFriendshipStatus(GetFriendshipStatusRequest) returns (GetFriendshipStatusResponse) {};
  rpc SendFriendReq(SendFriendReqRequest) returns (SendFriendReqResponse) {};
  rpc CancelFriendReq(CancelFriendReqRequest) returns (CancelFriendReqResponse) {};
  rpc AcceptFriendReq(AcceptFriendReqRequest) returns (AcceptFriendReqResponse) {};
}

enum FriendshipStatus {
  FRIENDSHIP_STATUS_UNSPECIFIED = 0;
  FRIENDSHIP_STATUS_FRIEND = 1;
  FRIENDSHIP_STATUS_REQUESTED = 2;
  FRIENDSHIP_STATUS_RECEIVED_REQUEST = 3;
  FRIENDSHIP_STATUS_NOTHING = 4;
}

message GetFriendshipStatusRequest {
  int64 toPerson = 1;
}

message GetFriendshipStatusResponse {
  FriendshipStatus fstatus=1;
}

message SearchForUsernameRequest {
  string look_for = 1;
}

message SearchForUsernameResponse {
  repeated account.v1.Account FoundUsers = 1;
}

message SendFriendReqRequest {
  int64 toPerson = 1;
}

message SendFriendReqResponse {
  bool success = 1;
}

message CancelFriendReqRequest {
  int64 toPerson = 1;
}

message CancelFriendReqResponse {
  bool success = 1;
}

message AcceptFriendReqRequest {
  int64 fromPerson = 1;
}

message AcceptFriendReqResponse {
  bool success = 1;
}
