// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const doesChatExist = `-- name: DoesChatExist :one
SELECT c.id
FROM chats c
JOIN chat_participants p1 ON p1.chat_id = c.id
JOIN chat_participants p2 ON p2.chat_id = c.id
WHERE c.type = 'direct'
  AND p1.user_id = $1
  AND p2.user_id = $2
`

type DoesChatExistParams struct {
	UserID   int
	UserID_2 int
}

func (q *Queries) DoesChatExist(ctx context.Context, arg DoesChatExistParams) (int, error) {
	row := q.db.QueryRow(ctx, doesChatExist, arg.UserID, arg.UserID_2)
	var id int
	err := row.Scan(&id)
	return id, err
}

const getAllChatsOfUser = `-- name: GetAllChatsOfUser :many
SELECT c.id, c.type, c.name, c.created_by, c.created_at, c.updated_at, c.deleted_at
FROM chats c
JOIN chat_participants p ON p.chat_id = c.id
WHERE p.user_id = 123 AND p.left_at IS NULL
`

func (q *Queries) GetAllChatsOfUser(ctx context.Context) ([]Chat, error) {
	rows, err := q.db.Query(ctx, getAllChatsOfUser)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chat
	for rows.Next() {
		var i Chat
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Name,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLastMessagesOfChat = `-- name: GetLastMessagesOfChat :many
SELECT id, chat_id, sender_user_id, content, reply_to_message_id, sent_at, edited_at, deleted_at FROM chat_messages
WHERE chat_id = $1 AND deleted_at IS NULL
ORDER BY sent_at DESC
LIMIT 20
`

func (q *Queries) GetLastMessagesOfChat(ctx context.Context, chatID int) ([]ChatMessage, error) {
	rows, err := q.db.Query(ctx, getLastMessagesOfChat, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatMessage
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.SenderUserID,
			&i.Content,
			&i.ReplyToMessageID,
			&i.SentAt,
			&i.EditedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setLastReadId = `-- name: SetLastReadId :exec
UPDATE chat_participants
SET last_read_message_id = $1
WHERE chat_id = $2 AND user_id = $3
`

type SetLastReadIdParams struct {
	LastReadMessageID pgtype.Int8
	ChatID            int
	UserID            int
}

func (q *Queries) SetLastReadId(ctx context.Context, arg SetLastReadIdParams) error {
	_, err := q.db.Exec(ctx, setLastReadId, arg.LastReadMessageID, arg.ChatID, arg.UserID)
	return err
}
