// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrGetChatRoom = `-- name: CreateOrGetChatRoom :one
INSERT INTO chat_rooms DEFAULT VALUES RETURNING chat_room_id, created_at, updated_at, deleted_at
`

func (q *Queries) CreateOrGetChatRoom(ctx context.Context) (ChatRoom, error) {
	row := q.db.QueryRow(ctx, createOrGetChatRoom)
	var i ChatRoom
	err := row.Scan(
		&i.ChatRoomID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const doesChatExist = `-- name: DoesChatExist :one
SELECT c.chat_room_id
FROM chat_rooms c
JOIN chat_participants p1 ON p1.chat_room_id_ref = c.chat_room_id
JOIN chat_participants p2 ON p2.chat_room_id_ref = c.chat_room_id
  AND p1.person_id = $1
  AND p2.person_id = $2
`

type DoesChatExistParams struct {
	PersonID   int
	PersonID_2 int
}

func (q *Queries) DoesChatExist(ctx context.Context, arg DoesChatExistParams) (int, error) {
	row := q.db.QueryRow(ctx, doesChatExist, arg.PersonID, arg.PersonID_2)
	var chat_room_id int
	err := row.Scan(&chat_room_id)
	return chat_room_id, err
}

const getAllChatsOfUser = `-- name: GetAllChatsOfUser :many
SELECT c.chat_room_id, c.created_at, c.updated_at, c.deleted_at
FROM chat_rooms c
JOIN chat_participants p ON p.chat_room_id_ref = c.chat_room_id
WHERE p.person_id = $1 AND p.left_at IS NULL
`

func (q *Queries) GetAllChatsOfUser(ctx context.Context, personID int) ([]ChatRoom, error) {
	rows, err := q.db.Query(ctx, getAllChatsOfUser, personID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatRoom
	for rows.Next() {
		var i ChatRoom
		if err := rows.Scan(
			&i.ChatRoomID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLastMessagesOfChat = `-- name: GetLastMessagesOfChat :many
SELECT message_id, chat_room_id_ref, sender_person_id, content, reply_to_message_id, sent_at, deleted_at, metadata FROM chat_messages
WHERE chat_room_id_ref = $1 AND deleted_at IS NULL
ORDER BY sent_at DESC
LIMIT 20
`

func (q *Queries) GetLastMessagesOfChat(ctx context.Context, chatRoomIDRef int) ([]ChatMessage, error) {
	rows, err := q.db.Query(ctx, getLastMessagesOfChat, chatRoomIDRef)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatMessage
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.MessageID,
			&i.ChatRoomIDRef,
			&i.SenderPersonID,
			&i.Content,
			&i.ReplyToMessageID,
			&i.SentAt,
			&i.DeletedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessagesOfChat = `-- name: GetMessagesOfChat :many
SELECT message_id, chat_room_id_ref, sender_person_id, content, reply_to_message_id, sent_at, deleted_at, metadata FROM chat_messages
WHERE chat_room_id_ref = $1 AND deleted_at IS NULL
ORDER BY sent_at DESC
LIMIT 20
`

func (q *Queries) GetMessagesOfChat(ctx context.Context, chatRoomIDRef int) ([]ChatMessage, error) {
	rows, err := q.db.Query(ctx, getMessagesOfChat, chatRoomIDRef)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatMessage
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.MessageID,
			&i.ChatRoomIDRef,
			&i.SenderPersonID,
			&i.Content,
			&i.ReplyToMessageID,
			&i.SentAt,
			&i.DeletedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertChatMessage = `-- name: InsertChatMessage :one
INSERT INTO chat_messages (chat_room_id_ref, sender_person_id, content, metadata)
VALUES ($1, $2, $3, $4)
RETURNING message_id, chat_room_id_ref, sender_person_id, content, reply_to_message_id, sent_at, deleted_at, metadata
`

type InsertChatMessageParams struct {
	ChatRoomIDRef  int
	SenderPersonID int
	Content        string
	Metadata       []byte
}

func (q *Queries) InsertChatMessage(ctx context.Context, arg InsertChatMessageParams) (ChatMessage, error) {
	row := q.db.QueryRow(ctx, insertChatMessage,
		arg.ChatRoomIDRef,
		arg.SenderPersonID,
		arg.Content,
		arg.Metadata,
	)
	var i ChatMessage
	err := row.Scan(
		&i.MessageID,
		&i.ChatRoomIDRef,
		&i.SenderPersonID,
		&i.Content,
		&i.ReplyToMessageID,
		&i.SentAt,
		&i.DeletedAt,
		&i.Metadata,
	)
	return i, err
}

const insertChatParticipants = `-- name: InsertChatParticipants :exec
INSERT INTO chat_participants (chat_room_id_ref, person_id)
VALUES ($1, $2)
ON CONFLICT (chat_room_id_ref, person_id) DO NOTHING
`

type InsertChatParticipantsParams struct {
	ChatRoomIDRef int
	PersonID      int
}

func (q *Queries) InsertChatParticipants(ctx context.Context, arg InsertChatParticipantsParams) error {
	_, err := q.db.Exec(ctx, insertChatParticipants, arg.ChatRoomIDRef, arg.PersonID)
	return err
}

const isChatParticipant = `-- name: IsChatParticipant :one
SELECT participant_id, chat_room_id_ref, person_id, joined_at, left_at, last_read_message_id FROM chat_participants
WHERE chat_room_id_ref = $1 AND person_id = $2
`

type IsChatParticipantParams struct {
	ChatRoomIDRef int
	PersonID      int
}

func (q *Queries) IsChatParticipant(ctx context.Context, arg IsChatParticipantParams) (ChatParticipant, error) {
	row := q.db.QueryRow(ctx, isChatParticipant, arg.ChatRoomIDRef, arg.PersonID)
	var i ChatParticipant
	err := row.Scan(
		&i.ParticipantID,
		&i.ChatRoomIDRef,
		&i.PersonID,
		&i.JoinedAt,
		&i.LeftAt,
		&i.LastReadMessageID,
	)
	return i, err
}

const markMessageAsRead = `-- name: MarkMessageAsRead :exec
UPDATE chat_messages
SET read_at = NOW()
WHERE message_id = $1
`

func (q *Queries) MarkMessageAsRead(ctx context.Context, messageID int) error {
	_, err := q.db.Exec(ctx, markMessageAsRead, messageID)
	return err
}

const setLastReadId = `-- name: SetLastReadId :exec
UPDATE chat_participants
SET last_read_message_id = $1
WHERE chat_room_id_ref = $2 AND person_id = $3
`

type SetLastReadIdParams struct {
	LastReadMessageID pgtype.Int8
	ChatRoomIDRef     int
	PersonID          int
}

func (q *Queries) SetLastReadId(ctx context.Context, arg SetLastReadIdParams) error {
	_, err := q.db.Exec(ctx, setLastReadId, arg.LastReadMessageID, arg.ChatRoomIDRef, arg.PersonID)
	return err
}
