// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: friends_request.sql

package database

import (
	"context"
)

const acceptFriendRequest = `-- name: AcceptFriendRequest :exec
UPDATE friend_requests
SET status = 'accepted', updated_at = NOW()
WHERE id = $1 AND status = 'pending'
`

func (q *Queries) AcceptFriendRequest(ctx context.Context, id int) error {
	_, err := q.db.Exec(ctx, acceptFriendRequest, id)
	return err
}

const getPersonsFriends = `-- name: GetPersonsFriends :many
SELECT 
    CASE 
        WHEN fr.sender_id = $1 THEN fr.receiver_id
        ELSE fr.sender_id
    END AS friend_id
FROM friend_requests fr
WHERE (fr.sender_id = $1 OR fr.receiver_id = $1)
  AND fr.status = 'accepted'
`

func (q *Queries) GetPersonsFriends(ctx context.Context, senderID int) ([]interface{}, error) {
	rows, err := q.db.Query(ctx, getPersonsFriends, senderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []interface{}
	for rows.Next() {
		var friend_id interface{}
		if err := rows.Scan(&friend_id); err != nil {
			return nil, err
		}
		items = append(items, friend_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertFriendRequest = `-- name: InsertFriendRequest :exec
INSERT INTO friend_requests (sender_id, receiver_id)
VALUES ($1, $2)
ON CONFLICT (sender_id, receiver_id) DO NOTHING
`

type InsertFriendRequestParams struct {
	SenderID   int
	ReceiverID int
}

func (q *Queries) InsertFriendRequest(ctx context.Context, arg InsertFriendRequestParams) error {
	_, err := q.db.Exec(ctx, insertFriendRequest, arg.SenderID, arg.ReceiverID)
	return err
}

const rejectFriendRequest = `-- name: RejectFriendRequest :exec
UPDATE friend_requests
SET status = 'rejected', updated_at = NOW()
WHERE id = $1 AND status = 'pending'
`

func (q *Queries) RejectFriendRequest(ctx context.Context, id int) error {
	_, err := q.db.Exec(ctx, rejectFriendRequest, id)
	return err
}
