// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: friends.sql

package database

import (
	"context"
)

const acceptFriendRequest = `-- name: AcceptFriendRequest :exec
UPDATE friend_requests
SET status = 'accepted', updated_at = NOW()
WHERE sender_id = $1 AND receiver_id=$2 AND status = 'pending'
`

type AcceptFriendRequestParams struct {
	SenderID   int
	ReceiverID int
}

func (q *Queries) AcceptFriendRequest(ctx context.Context, arg AcceptFriendRequestParams) error {
	_, err := q.db.Exec(ctx, acceptFriendRequest, arg.SenderID, arg.ReceiverID)
	return err
}

const cancelFriendRequest = `-- name: CancelFriendRequest :one
UPDATE friend_requests
SET status = 'canceled' WHERE sender_id=$1 AND receiver_id=$2 RETURNING id, sender_id, receiver_id, status, created_at, updated_at
`

type CancelFriendRequestParams struct {
	SenderID   int
	ReceiverID int
}

func (q *Queries) CancelFriendRequest(ctx context.Context, arg CancelFriendRequestParams) (FriendRequest, error) {
	row := q.db.QueryRow(ctx, cancelFriendRequest, arg.SenderID, arg.ReceiverID)
	var i FriendRequest
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.ReceiverID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const checkFriendship = `-- name: CheckFriendship :one
SELECT EXISTS (
    SELECT 1 FROM friends 
    WHERE (user_id = $1 AND friend_id = $2)
       OR (user_id = $2 AND friend_id = $1)
) AS is_friend
`

type CheckFriendshipParams struct {
	UserID   int
	FriendID int
}

func (q *Queries) CheckFriendship(ctx context.Context, arg CheckFriendshipParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkFriendship, arg.UserID, arg.FriendID)
	var is_friend bool
	err := row.Scan(&is_friend)
	return is_friend, err
}

const getFriendshipStatus = `-- name: GetFriendshipStatus :one
SELECT 
    CASE 
        WHEN EXISTS (
            SELECT 1 FROM friends 
            WHERE (user_id = $1 AND friend_id = $2)
               OR (user_id = $2 AND friend_id = $1)
        ) THEN 'friends'
        WHEN EXISTS (
            SELECT 1 FROM friend_requests 
            WHERE sender_id = $1 AND receiver_id = $2 AND status = 'pending'
        ) THEN 'request_sent'
        WHEN EXISTS (
            SELECT 1 FROM friend_requests 
            WHERE sender_id = $2 AND receiver_id = $1 AND status = 'pending'
        ) THEN 'request_received'
        ELSE 'not_connected'
    END AS status
`

type GetFriendshipStatusParams struct {
	UserID   int
	FriendID int
}

func (q *Queries) GetFriendshipStatus(ctx context.Context, arg GetFriendshipStatusParams) (string, error) {
	row := q.db.QueryRow(ctx, getFriendshipStatus, arg.UserID, arg.FriendID)
	var status string
	err := row.Scan(&status)
	return status, err
}

const getPersonFriends = `-- name: GetPersonFriends :many
SELECT f1.friend_id FROM friends f1 WHERE f1.user_id=$1
UNION 
SELECT f2.user_id FROM friends f2 WHERE f2.friend_id=$1
`

func (q *Queries) GetPersonFriends(ctx context.Context, userID int) ([]int, error) {
	rows, err := q.db.Query(ctx, getPersonFriends, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int
	for rows.Next() {
		var friend_id int
		if err := rows.Scan(&friend_id); err != nil {
			return nil, err
		}
		items = append(items, friend_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPersonsFriendsRequest = `-- name: GetPersonsFriendsRequest :many
SELECT 
    CASE 
        WHEN fr.sender_id = $1 THEN fr.receiver_id
        ELSE fr.sender_id
    END AS friend_id
FROM friend_requests fr
WHERE (fr.sender_id = $1 OR fr.receiver_id = $1)
  AND fr.status = 'accepted'
`

func (q *Queries) GetPersonsFriendsRequest(ctx context.Context, senderID int) ([]interface{}, error) {
	rows, err := q.db.Query(ctx, getPersonsFriendsRequest, senderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []interface{}
	for rows.Next() {
		var friend_id interface{}
		if err := rows.Scan(&friend_id); err != nil {
			return nil, err
		}
		items = append(items, friend_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertFriend = `-- name: InsertFriend :exec
INSERT INTO friends (user_id, friend_id)
VALUES ($1, $2)
ON CONFLICT (user_id, friend_id) DO NOTHING
`

type InsertFriendParams struct {
	UserID   int
	FriendID int
}

func (q *Queries) InsertFriend(ctx context.Context, arg InsertFriendParams) error {
	_, err := q.db.Exec(ctx, insertFriend, arg.UserID, arg.FriendID)
	return err
}

const insertFriendRequest = `-- name: InsertFriendRequest :exec
INSERT INTO friend_requests (sender_id, receiver_id)
VALUES ($1, $2)
ON CONFLICT (sender_id, receiver_id) 
WHERE status = 'pending' 
DO NOTHING
`

type InsertFriendRequestParams struct {
	SenderID   int
	ReceiverID int
}

func (q *Queries) InsertFriendRequest(ctx context.Context, arg InsertFriendRequestParams) error {
	_, err := q.db.Exec(ctx, insertFriendRequest, arg.SenderID, arg.ReceiverID)
	return err
}

const rejectFriendRequest = `-- name: RejectFriendRequest :exec
UPDATE friend_requests
SET status = 'rejected', updated_at = NOW()
WHERE id = $1 AND status = 'pending'
`

func (q *Queries) RejectFriendRequest(ctx context.Context, id int) error {
	_, err := q.db.Exec(ctx, rejectFriendRequest, id)
	return err
}
