// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invite_rooms.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countInviteRoomPlayers = `-- name: CountInviteRoomPlayers :one
SELECT COUNT(*)::bigint
FROM invite_room_players
WHERE room_id = $1
`

func (q *Queries) CountInviteRoomPlayers(ctx context.Context, roomID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countInviteRoomPlayers, roomID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteInviteRoom = `-- name: DeleteInviteRoom :exec
DELETE FROM invite_rooms
WHERE id = $1
`

func (q *Queries) DeleteInviteRoom(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteInviteRoom, id)
	return err
}

const deleteInviteRoomPlayer = `-- name: DeleteInviteRoomPlayer :exec
DELETE FROM invite_room_players
WHERE room_id = $1 AND person_id = $2
`

type DeleteInviteRoomPlayerParams struct {
	RoomID   int64
	PersonID int64
}

func (q *Queries) DeleteInviteRoomPlayer(ctx context.Context, arg DeleteInviteRoomPlayerParams) error {
	_, err := q.db.Exec(ctx, deleteInviteRoomPlayer, arg.RoomID, arg.PersonID)
	return err
}

const getInviteRoomByCode = `-- name: GetInviteRoomByCode :one
SELECT id, invite_code, game_key, host_person_id, created_at, expires_at
FROM invite_rooms
WHERE invite_code = $1 AND expires_at > NOW()
`

func (q *Queries) GetInviteRoomByCode(ctx context.Context, inviteCode string) (InviteRoom, error) {
	row := q.db.QueryRow(ctx, getInviteRoomByCode, inviteCode)
	var i InviteRoom
	err := row.Scan(
		&i.ID,
		&i.InviteCode,
		&i.GameKey,
		&i.HostPersonID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getInviteRoomForPerson = `-- name: GetInviteRoomForPerson :one
SELECT r.id, r.invite_code, r.game_key, r.host_person_id, r.created_at, r.expires_at
FROM invite_room_players irp
JOIN invite_rooms r ON r.id = irp.room_id
WHERE irp.person_id = $1 AND r.expires_at > NOW()
LIMIT 1
`

func (q *Queries) GetInviteRoomForPerson(ctx context.Context, personID int64) (InviteRoom, error) {
	row := q.db.QueryRow(ctx, getInviteRoomForPerson, personID)
	var i InviteRoom
	err := row.Scan(
		&i.ID,
		&i.InviteCode,
		&i.GameKey,
		&i.HostPersonID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const insertInviteRoom = `-- name: InsertInviteRoom :one
INSERT INTO invite_rooms (invite_code, game_key, host_person_id, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, invite_code, game_key, host_person_id, created_at, expires_at
`

type InsertInviteRoomParams struct {
	InviteCode   string
	GameKey      string
	HostPersonID int64
	ExpiresAt    pgtype.Timestamp
}

func (q *Queries) InsertInviteRoom(ctx context.Context, arg InsertInviteRoomParams) (InviteRoom, error) {
	row := q.db.QueryRow(ctx, insertInviteRoom,
		arg.InviteCode,
		arg.GameKey,
		arg.HostPersonID,
		arg.ExpiresAt,
	)
	var i InviteRoom
	err := row.Scan(
		&i.ID,
		&i.InviteCode,
		&i.GameKey,
		&i.HostPersonID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const insertInviteRoomPlayer = `-- name: InsertInviteRoomPlayer :exec
INSERT INTO invite_room_players (room_id, person_id)
VALUES ($1, $2)
ON CONFLICT (room_id, person_id) DO NOTHING
`

type InsertInviteRoomPlayerParams struct {
	RoomID   int64
	PersonID int64
}

func (q *Queries) InsertInviteRoomPlayer(ctx context.Context, arg InsertInviteRoomPlayerParams) error {
	_, err := q.db.Exec(ctx, insertInviteRoomPlayer, arg.RoomID, arg.PersonID)
	return err
}

const listInviteRoomPlayers = `-- name: ListInviteRoomPlayers :many
SELECT p.id, p.display_name, p.username, p.coins, p.is_guest, p.merged_at, p.updated_at, p.created_at
FROM invite_room_players irp
JOIN persons p ON p.id = irp.person_id
WHERE irp.room_id = $1
ORDER BY irp.joined_at ASC
`

func (q *Queries) ListInviteRoomPlayers(ctx context.Context, roomID int64) ([]Person, error) {
	rows, err := q.db.Query(ctx, listInviteRoomPlayers, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Person
	for rows.Next() {
		var i Person
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Username,
			&i.Coins,
			&i.IsGuest,
			&i.MergedAt,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
