// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ChatType string

const (
	ChatTypeDirect ChatType = "direct"
	ChatTypeGroup  ChatType = "group"
)

func (e *ChatType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ChatType(s)
	case string:
		*e = ChatType(s)
	default:
		return fmt.Errorf("unsupported scan type for ChatType: %T", src)
	}
	return nil
}

type NullChatType struct {
	ChatType ChatType
	Valid    bool // Valid is true if ChatType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullChatType) Scan(value interface{}) error {
	if value == nil {
		ns.ChatType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ChatType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullChatType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ChatType), nil
}

type Chat struct {
	ID        int
	Type      ChatType
	Name      pgtype.Text
	CreatedBy int
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type ChatMessage struct {
	ID               int
	ChatID           int
	SenderUserID     int
	Content          string
	ReplyToMessageID pgtype.Int8
	SentAt           pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
}

type ChatParticipant struct {
	ID                int
	ChatID            int
	UserID            int
	Role              string
	JoinedAt          pgtype.Timestamptz
	LeftAt            pgtype.Timestamptz
	LastReadMessageID pgtype.Int8
}

type Friend struct {
	ID        int
	UserID    int
	FriendID  int
	CreatedAt pgtype.Timestamptz
}

type FriendRequest struct {
	ID         int
	SenderID   int
	ReceiverID int
	Status     string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type Game struct {
	ID          int
	Name        string
	Slug        string
	Description pgtype.Text
	MinPlayers  pgtype.Int4
	MaxPlayers  pgtype.Int4
	CreatedAt   pgtype.Timestamptz
}

type MessageAttachment struct {
	ID        int
	MessageID int
	FileUrl   string
	FileType  pgtype.Text
	FileName  pgtype.Text
	FileSize  pgtype.Int8
}

type Person struct {
	ID          int
	DisplayName string
	Username    string
	Coins       int32
	IsGuest     bool
	MergedAt    pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	CreatedAt   pgtype.Timestamp
}

type PersonAuthMethod struct {
	ID        int
	UserID    int32
	AuthType  string
	AuthValue string
	CreatedAt pgtype.Timestamp
}

type Room struct {
	ID          int
	Name        string
	Rtype       string
	CreatedBy   int
	Createdmode string
	CreatedAt   pgtype.Timestamp
}

type RoomGame struct {
	ID        int
	RoomID    int
	GameType  string
	StartedAt pgtype.Timestamp
	EndedAt   pgtype.Timestamp
	Status    pgtype.Text
}

type RoomMessage struct {
	ID        int
	RoomID    int
	PersonID  int
	ReplyTo   pgtype.Int8
	Content   string
	IsEdited  pgtype.Bool
	EditedAt  pgtype.Timestamptz
	IsDeleted pgtype.Bool
	CreatedAt pgtype.Timestamptz
}

type RoomParticipant struct {
	RoomID            int
	UserID            int
	LastReadMessageID int
	JoinedAt          pgtype.Timestamptz
}

type RoomPlayer struct {
	ID       int
	RoomID   int
	PersonID int
}

type UserGameStat struct {
	UserID       int
	GameID       int
	Wins         pgtype.Int4
	Losses       pgtype.Int4
	Draws        pgtype.Int4
	EloRating    pgtype.Int4
	Xp           pgtype.Int4
	Level        pgtype.Int4
	LastPlayedAt pgtype.Timestamptz
}
