// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type InviteRoom struct {
	ID           int64
	InviteCode   string
	GameKey      string
	HostPersonID int64
	CreatedAt    pgtype.Timestamp
	ExpiresAt    pgtype.Timestamp
}

type InviteRoomPlayer struct {
	RoomID   int64
	PersonID int64
	JoinedAt pgtype.Timestamp
}

type Person struct {
	ID          int64
	DisplayName string
	Username    string
	Coins       int32
	IsGuest     bool
	MergedAt    pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	CreatedAt   pgtype.Timestamp
}

type PersonAuthMethod struct {
	ID        int64
	UserID    int64
	AuthType  string
	AuthValue string
	CreatedAt pgtype.Timestamp
}
