// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: persons.sql

package database

import (
	"context"
)

const getPersonByAuthMethod = `-- name: GetPersonByAuthMethod :one
SELECT p.id, p.display_name, p.username, p.coins, p.is_guest, p.merged_at, p.updated_at, p.created_at
FROM persons p
JOIN person_auth_methods pam ON p.id = pam.user_id
WHERE pam.auth_type = $1 AND pam.auth_value = $2
LIMIT 1
`

type GetPersonByAuthMethodParams struct {
	AuthType  string
	AuthValue string
}

func (q *Queries) GetPersonByAuthMethod(ctx context.Context, arg GetPersonByAuthMethodParams) (Person, error) {
	row := q.db.QueryRow(ctx, getPersonByAuthMethod, arg.AuthType, arg.AuthValue)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Username,
		&i.Coins,
		&i.IsGuest,
		&i.MergedAt,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPersonByID = `-- name: GetPersonByID :one
SELECT id, display_name, username, coins, is_guest, merged_at, updated_at, created_at
FROM persons
WHERE id = $1
`

func (q *Queries) GetPersonByID(ctx context.Context, id int64) (Person, error) {
	row := q.db.QueryRow(ctx, getPersonByID, id)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Username,
		&i.Coins,
		&i.IsGuest,
		&i.MergedAt,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertAuthMethod = `-- name: InsertAuthMethod :one
INSERT INTO person_auth_methods (user_id, auth_type, auth_value)
VALUES ($1, $2, $3)
RETURNING id, user_id, auth_type, auth_value, created_at
`

type InsertAuthMethodParams struct {
	UserID    int64
	AuthType  string
	AuthValue string
}

func (q *Queries) InsertAuthMethod(ctx context.Context, arg InsertAuthMethodParams) (PersonAuthMethod, error) {
	row := q.db.QueryRow(ctx, insertAuthMethod, arg.UserID, arg.AuthType, arg.AuthValue)
	var i PersonAuthMethod
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AuthType,
		&i.AuthValue,
		&i.CreatedAt,
	)
	return i, err
}

const insertPerson = `-- name: InsertPerson :one
INSERT INTO persons (username, display_name, is_guest)
VALUES ($1, $2, $3)
RETURNING id, display_name, username, coins, is_guest, merged_at, updated_at, created_at
`

type InsertPersonParams struct {
	Username    string
	DisplayName string
	IsGuest     bool
}

func (q *Queries) InsertPerson(ctx context.Context, arg InsertPersonParams) (Person, error) {
	row := q.db.QueryRow(ctx, insertPerson, arg.Username, arg.DisplayName, arg.IsGuest)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Username,
		&i.Coins,
		&i.IsGuest,
		&i.MergedAt,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}
