// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: persons.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveTgUsers = `-- name: CountActiveTgUsers :one



SELECT COUNT(*) FROM persons
WHERE is_active = TRUE
`

// -- name: CreateTgUser :one
// INSERT INTO persons (tg_id,name)
// VALUES ($1,$2)
// ON CONFLICT (tg_id) DO UPDATE
// SET updated_at = NOW(),
//
//	is_active = TRUE
//
// RETURNING *;
func (q *Queries) CountActiveTgUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveTgUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAllTgUsers = `-- name: CountAllTgUsers :one
SELECT COUNT(*) FROM persons
`

func (q *Queries) CountAllTgUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllTgUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersTgCreatedBetween = `-- name: CountUsersTgCreatedBetween :one
SELECT COUNT(*) FROM persons
WHERE created_at >= $1 AND created_at <= $2
`

type CountUsersTgCreatedBetweenParams struct {
	CreatedAt   pgtype.Timestamp
	CreatedAt_2 pgtype.Timestamp
}

func (q *Queries) CountUsersTgCreatedBetween(ctx context.Context, arg CountUsersTgCreatedBetweenParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersTgCreatedBetween, arg.CreatedAt, arg.CreatedAt_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAllTgUsers = `-- name: GetAllTgUsers :many


SELECT id, display_name, username, coins, is_guest, merged_at, updated_at, created_at FROM persons
`

// -- name: GetTgUserByTgID :one
// SELECT * FROM persons
// WHERE tg_id = $1;
func (q *Queries) GetAllTgUsers(ctx context.Context) ([]Person, error) {
	rows, err := q.db.Query(ctx, getAllTgUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Person
	for rows.Next() {
		var i Person
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Username,
			&i.Coins,
			&i.IsGuest,
			&i.MergedAt,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPersonByAuthMethod = `-- name: GetPersonByAuthMethod :one
SELECT p.id, p.display_name, p.username, p.coins, p.is_guest, p.merged_at, p.updated_at, p.created_at FROM persons p
JOIN person_auth_methods pam ON p.id = pam.user_id
WHERE pam.auth_type = $1 AND pam.auth_value = $2
LIMIT 1
`

type GetPersonByAuthMethodParams struct {
	AuthType  string
	AuthValue string
}

func (q *Queries) GetPersonByAuthMethod(ctx context.Context, arg GetPersonByAuthMethodParams) (Person, error) {
	row := q.db.QueryRow(ctx, getPersonByAuthMethod, arg.AuthType, arg.AuthValue)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Username,
		&i.Coins,
		&i.IsGuest,
		&i.MergedAt,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPersonByID = `-- name: GetPersonByID :one
SELECT id, display_name, username, coins, is_guest, merged_at, updated_at, created_at FROM persons
WHERE id = $1
`

func (q *Queries) GetPersonByID(ctx context.Context, id int) (Person, error) {
	row := q.db.QueryRow(ctx, getPersonByID, id)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Username,
		&i.Coins,
		&i.IsGuest,
		&i.MergedAt,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPersonsByIDs = `-- name: GetPersonsByIDs :many
SELECT p.id, p.display_name, p.username, p.coins, p.is_guest, p.merged_at, p.updated_at, p.created_at
FROM persons p
JOIN unnest($1::bigint[]) WITH ORDINALITY AS t(id, ord)
    ON p.id = t.id
ORDER BY t.ord
`

func (q *Queries) GetPersonsByIDs(ctx context.Context, dollar_1 []int) ([]Person, error) {
	rows, err := q.db.Query(ctx, getPersonsByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Person
	for rows.Next() {
		var i Person
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Username,
			&i.Coins,
			&i.IsGuest,
			&i.MergedAt,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTgUsersStatic = `-- name: GetTgUsersStatic :one
SELECT
  COUNT(*) FILTER (WHERE is_active = TRUE) AS active_users,
  COUNT(*) AS total_users,
  COUNT(*) FILTER ( WHERE created_at >= NOW() - INTERVAL '1 day') AS users_created_last_24_hours,
  COUNT(*) FILTER ( WHERE created_at >= NOW() - INTERVAL '7 days') AS users_created_last_week,
  COUNT(*) FILTER ( WHERE created_at >= NOW() - INTERVAL '1 month') AS users_created_last_month
FROM persons
`

type GetTgUsersStaticRow struct {
	ActiveUsers             int64
	TotalUsers              int64
	UsersCreatedLast24Hours int64
	UsersCreatedLastWeek    int64
	UsersCreatedLastMonth   int64
}

func (q *Queries) GetTgUsersStatic(ctx context.Context) (GetTgUsersStaticRow, error) {
	row := q.db.QueryRow(ctx, getTgUsersStatic)
	var i GetTgUsersStaticRow
	err := row.Scan(
		&i.ActiveUsers,
		&i.TotalUsers,
		&i.UsersCreatedLast24Hours,
		&i.UsersCreatedLastWeek,
		&i.UsersCreatedLastMonth,
	)
	return i, err
}

const getUserMethod = `-- name: GetUserMethod :one
SELECT user_id FROM person_auth_methods 
WHERE auth_type = $1 AND auth_value = $2
`

type GetUserMethodParams struct {
	AuthType  string
	AuthValue string
}

func (q *Queries) GetUserMethod(ctx context.Context, arg GetUserMethodParams) (int32, error) {
	row := q.db.QueryRow(ctx, getUserMethod, arg.AuthType, arg.AuthValue)
	var user_id int32
	err := row.Scan(&user_id)
	return user_id, err
}

const insertAuthMethod = `-- name: InsertAuthMethod :one
INSERT INTO person_auth_methods (user_id,auth_type,auth_value)
VALUES ($1, $2, $3) RETURNING id, user_id, auth_type, auth_value, created_at
`

type InsertAuthMethodParams struct {
	UserID    int32
	AuthType  string
	AuthValue string
}

func (q *Queries) InsertAuthMethod(ctx context.Context, arg InsertAuthMethodParams) (PersonAuthMethod, error) {
	row := q.db.QueryRow(ctx, insertAuthMethod, arg.UserID, arg.AuthType, arg.AuthValue)
	var i PersonAuthMethod
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AuthType,
		&i.AuthValue,
		&i.CreatedAt,
	)
	return i, err
}

const insertPerson = `-- name: InsertPerson :one
INSERT INTO persons (username,display_name, is_guest)
VALUES ($1,$2, $3) RETURNING id, display_name, username, coins, is_guest, merged_at, updated_at, created_at
`

type InsertPersonParams struct {
	Username    string
	DisplayName string
	IsGuest     bool
}

func (q *Queries) InsertPerson(ctx context.Context, arg InsertPersonParams) (Person, error) {
	row := q.db.QueryRow(ctx, insertPerson, arg.Username, arg.DisplayName, arg.IsGuest)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Username,
		&i.Coins,
		&i.IsGuest,
		&i.MergedAt,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const searchPersonByUsername = `-- name: SearchPersonByUsername :many
SELECT id,username,display_name FROM persons
WHERE username LIKE $1 || '%' ORDER BY username LIMIT 5
`

type SearchPersonByUsernameRow struct {
	ID          int
	Username    string
	DisplayName string
}

func (q *Queries) SearchPersonByUsername(ctx context.Context, dollar_1 pgtype.Text) ([]SearchPersonByUsernameRow, error) {
	rows, err := q.db.Query(ctx, searchPersonByUsername, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchPersonByUsernameRow
	for rows.Next() {
		var i SearchPersonByUsernameRow
		if err := rows.Scan(&i.ID, &i.Username, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMixedTgUserStatuses = `-- name: UpdateMixedTgUserStatuses :exec

UPDATE persons
SET is_active = CASE
  WHEN id = ANY ($1::bigint[]) THEN TRUE
  ELSE FALSE  
END
`

// -- name: ActiveTgUser :exec
// UPDATE persons SET is_active = TRUE
// WHERE (
//
//	tg_id = $1
//
// );
//
// -- name: DiactiveTgUser :exec
// UPDATE persons SET is_active = FALSE
// WHERE (
//
//	tg_id = $1
//
// );
func (q *Queries) UpdateMixedTgUserStatuses(ctx context.Context, dollar_1 []int) error {
	_, err := q.db.Exec(ctx, updateMixedTgUserStatuses, dollar_1)
	return err
}
