// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rooms.sql

package database

import (
	"context"
)

const countLastDayRoomss = `-- name: CountLastDayRoomss :one
SELECT COUNT(*) AS games_today
FROM rooms
WHERE created_at >= date_trunc('day', NOW())
`

func (q *Queries) CountLastDayRoomss(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countLastDayRoomss)
	var games_today int64
	err := row.Scan(&games_today)
	return games_today, err
}

const countLastHourHub = `-- name: CountLastHourHub :one
SELECT COUNT(*) AS hubs_last_hour
FROM rooms
WHERE created_at >= NOW() - INTERVAL '1 hour'
`

func (q *Queries) CountLastHourHub(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countLastHourHub)
	var hubs_last_hour int64
	err := row.Scan(&hubs_last_hour)
	return hubs_last_hour, err
}

const countRooms = `-- name: CountRooms :one
Select Count(*) from rooms
`

func (q *Queries) CountRooms(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countRooms)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRoom = `-- name: CreateRoom :one
INSERT INTO rooms (createdMode) VALUES ($1) RETURNING id, createdmode, created_at
`

func (q *Queries) CreateRoom(ctx context.Context, createdmode string) (Room, error) {
	row := q.db.QueryRow(ctx, createRoom, createdmode)
	var i Room
	err := row.Scan(&i.ID, &i.Createdmode, &i.CreatedAt)
	return i, err
}
