// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rooms.sql

package database

import (
	"context"
)

const deleteRoomPlayer = `-- name: DeleteRoomPlayer :exec
DELETE FROM room_players WHERE room_id = $1 AND person_id = $2
`

type DeleteRoomPlayerParams struct {
	RoomID   int64
	PersonID int64
}

func (q *Queries) DeleteRoomPlayer(ctx context.Context, arg DeleteRoomPlayerParams) error {
	_, err := q.db.Exec(ctx, deleteRoomPlayer, arg.RoomID, arg.PersonID)
	return err
}

const insertRoom = `-- name: InsertRoom :one
INSERT INTO rooms
DEFAULT VALUES
RETURNING id, created_at, updated_at
`

func (q *Queries) InsertRoom(ctx context.Context) (Room, error) {
	row := q.db.QueryRow(ctx, insertRoom)
	var i Room
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const insertRoomPlayer = `-- name: InsertRoomPlayer :one
INSERT INTO room_players (room_id, person_id)
VALUES ($1, $2)
ON CONFLICT (room_id, person_id) DO NOTHING
RETURNING id, room_id, person_id, joined_at
`

type InsertRoomPlayerParams struct {
	RoomID   int64
	PersonID int64
}

func (q *Queries) InsertRoomPlayer(ctx context.Context, arg InsertRoomPlayerParams) (RoomPlayer, error) {
	row := q.db.QueryRow(ctx, insertRoomPlayer, arg.RoomID, arg.PersonID)
	var i RoomPlayer
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.PersonID,
		&i.JoinedAt,
	)
	return i, err
}
