// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: room_messages.sql

package database

import (
	"context"
)

const getRoomMessages = `-- name: GetRoomMessages :many
SELECT id, room_id, person_id, message, created_at
FROM room_messages
WHERE room_id = $1
ORDER BY created_at ASC LIMIT $2 OFFSET $3
`

type GetRoomMessagesParams struct {
	RoomID int64
	Limit  int32
	Offset int32
}

func (q *Queries) GetRoomMessages(ctx context.Context, arg GetRoomMessagesParams) ([]RoomMessage, error) {
	rows, err := q.db.Query(ctx, getRoomMessages, arg.RoomID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RoomMessage
	for rows.Next() {
		var i RoomMessage
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.PersonID,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertRoomMessage = `-- name: InsertRoomMessage :one
INSERT INTO room_messages (room_id, person_id, message)
VALUES ($1, $2, $3)
RETURNING id, room_id, person_id, message, created_at
`

type InsertRoomMessageParams struct {
	RoomID   int64
	PersonID int64
	Message  string
}

func (q *Queries) InsertRoomMessage(ctx context.Context, arg InsertRoomMessageParams) (RoomMessage, error) {
	row := q.db.QueryRow(ctx, insertRoomMessage, arg.RoomID, arg.PersonID, arg.Message)
	var i RoomMessage
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.PersonID,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}
