// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: room_messages.sql

package database

import (
	"context"
)

const createRoomMessage = `-- name: CreateRoomMessage :one
INSERT INTO room_messages (room_id,player_id,message) VALUES ($1,$2,$3) RETURNING id, room_id, player_id, message, sent_at
`

type CreateRoomMessageParams struct {
	RoomID   int
	PlayerID int
	Message  string
}

func (q *Queries) CreateRoomMessage(ctx context.Context, arg CreateRoomMessageParams) (RoomMessage, error) {
	row := q.db.QueryRow(ctx, createRoomMessage, arg.RoomID, arg.PlayerID, arg.Message)
	var i RoomMessage
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.PlayerID,
		&i.Message,
		&i.SentAt,
	)
	return i, err
}

const getRoomMessages = `-- name: GetRoomMessages :many
SELECT id, room_id, player_id, message, sent_at
FROM room_messages
WHERE room_id = $1
ORDER BY id DESC
LIMIT $2
`

type GetRoomMessagesParams struct {
	RoomID int
	Limit  int32
}

func (q *Queries) GetRoomMessages(ctx context.Context, arg GetRoomMessagesParams) ([]RoomMessage, error) {
	rows, err := q.db.Query(ctx, getRoomMessages, arg.RoomID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RoomMessage
	for rows.Next() {
		var i RoomMessage
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.PlayerID,
			&i.Message,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
