// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: room_players.sql

package database

import (
	"context"
)

const createRoomPlayer = `-- name: CreateRoomPlayer :one
INSERT INTO room_players (room_id,person_id) VALUES ($1,$2) RETURNING id, room_id, person_id
`

type CreateRoomPlayerParams struct {
	RoomID   int
	PersonID int
}

func (q *Queries) CreateRoomPlayer(ctx context.Context, arg CreateRoomPlayerParams) (RoomPlayer, error) {
	row := q.db.QueryRow(ctx, createRoomPlayer, arg.RoomID, arg.PersonID)
	var i RoomPlayer
	err := row.Scan(&i.ID, &i.RoomID, &i.PersonID)
	return i, err
}
