syntax = "proto3";

package invite.v1;

import "account/v1/account.proto";

service InviteService {
  rpc CreateInviteRoom(CreateInviteRoomRequest) returns (CreateInviteRoomResponse);
  rpc JoinInviteRoom(JoinInviteRoomRequest) returns (JoinInviteRoomResponse);
  rpc GetInviteRoom(GetInviteRoomRequest) returns (GetInviteRoomResponse);
  rpc LeaveInviteRoom(LeaveInviteRoomRequest) returns (LeaveInviteRoomResponse);
}

message CreateInviteRoomRequest {
  string game_key = 1;
}

message CreateInviteRoomResponse {
  string invite_code = 1;
}

message JoinInviteRoomRequest {
  string invite_code = 1;
}

message JoinInviteRoomResponse {}

message GetInviteRoomRequest {
  string invite_code = 1;
}

message GetInviteRoomResponse {
  string invite_code = 1;
  string game_key = 2;
  // host
  account.v1.Account host_player = 3;
  repeated account.v1.Account players = 4;
}

message LeaveInviteRoomRequest {
  string invite_code = 1;
}

message LeaveInviteRoomResponse {
  bool ok = 1;
}
