syntax = "proto3";

package room.v1;

import "account/v1/account.proto";
import "tictac/v1/tictac.proto";

// GameType Message
enum GameType {
  GAME_TYPE_UNSPECIFIED = 0;
  GAME_TYPE_XO3X3 = 1;
  GAME_TYPE_XO5X5 = 2;
  GAME_TYPE_CONN4 = 3;
}

service RoomService {
  rpc CreateRoom(CreateRoomRequest) returns (CreateRoomResponse);
  rpc GetRoom(GetRoomRequest) returns (GetRoomResponse);
}

message CreateRoomRequest {
  string game_key = 1;
}

message CreateRoomResponse {
  string code = 1;
}

message GetRoomRequest {
  string code = 1;
}

message GetRoomResponse {
  string code = 1;
  string game_key = 2;
  account.v1.Account host_player = 3;
  repeated account.v1.Account players = 4;
}

message ChatMessageRequest {
  string text = 1;
}
message ChatMessageResponse {
  int64 player_id = 1;
  string text = 2;
  int64 id = 3;
}

message RoomMemberJoined {
  account.v1.Account player = 1;
}

message RoomMemberLeft {
  account.v1.Account player = 1;
}

message RoomMessage {
  oneof content {
    GameMessage game = 1;
    ChatMessageResponse chat = 2;
    ChatMessageRequest chat_req = 3;
    RoomErrorType error = 4;
    RoomMemberJoined member_joined = 5;
    RoomMemberLeft member_left = 6;

  }
}

enum RoomErrorType {
  ROOM_ERROR_TYPE_UNSPECIFIED = 0;
  ROOM_ERROR_TYPE_AUTH = 1;
  ROOM_ERROR_TYPE_NOROOM = 2;
  ROOM_ERROR_TYPE_INVALID_CODE = 3;
}


// Game Room
message GameMessage {
  oneof game {
    tictac.v1.TicTacToeGameMessage tictactoe = 1;
    // conn4_game.v1.Conn4GameMessage conn4 = 2;
  }
}
