syntax = "proto3";

package room.v1;

import "account/v1/account.proto";

service RoomService {
  rpc CreateRoom(CreateRoomRequest) returns (CreateRoomResponse);
  rpc JoinRoom(JoinRoomRequest) returns (JoinRoomResponse);
  rpc GetRoom(GetRoomRequest) returns (GetRoomResponse);
  rpc LeaveRoom(LeaveRoomRequest) returns (LeaveRoomResponse);
}

message CreateRoomRequest {
  string game_key = 1;
}

message CreateRoomResponse {
  string code = 1;
}

message JoinRoomRequest {
  string code = 1;
}

message JoinRoomResponse {}

message GetRoomRequest {
  string code = 1;
}

message GetRoomResponse {
  string code = 1;
  string game_key = 2;
  account.v1.Account host_player = 3;
  repeated account.v1.Account players = 4;
}

message LeaveRoomRequest {
  string code = 1;
}

message LeaveRoomResponse {
  bool ok = 1;
}


message ChatMessageRequest {
  string text = 1;
}
message ChatMessageResponse {
  int64 player_id = 1;
  string text = 2;
  int64 id = 3;
}


message RoomMessage {
  oneof content {
    ChatMessageResponse chat = 1;
    ChatMessageRequest chat_req = 2;
    RoomErrorType error = 4;
  }
}

enum RoomErrorType {
  ROOM_ERROR_TYPE_UNSPECIFIED = 0;
  ROOM_ERROR_TYPE_AUTH = 1;
  ROOM_ERROR_TYPE_NOROOM = 2;
  ROOM_ERROR_TYPE_INVALID_CODE = 3;
}
